FROM power10-mma-baseimage

RUN git clone https://github.com/MaximeDeloche/mqtt-realtime-chart-client /Kafka-DayTrader-AI-example/AI_Component/src/visualization

WORKDIR /Kafka-DayTrader-AI-example/AI_Component/src/visualization/mqtt-realtime-chart-client

RUN npm install

EXPOSE 9080

CMD ["npm", "start"]
