
--  Standards Option:          	Db2 for i 
CREATE OR REPLACE TABLE OCPDT.ACCOUNTPROFILEEJB FOR SYSTEM NAME ACCOU00001 ( 
	ADDRESS VARCHAR(250) CCSID 37 DEFAULT NULL , 
	PASSWD VARCHAR(250) CCSID 37 DEFAULT NULL , 
	"USERID" VARCHAR(250) CCSID 37 NOT NULL , 
	EMAIL VARCHAR(250) CCSID 37 DEFAULT NULL , 
	CREDITCARD VARCHAR(250) CCSID 37 DEFAULT NULL , 
	FULLNAME VARCHAR(250) CCSID 37 DEFAULT NULL , 
	CONSTRAINT OCPDT.PK_ACCOUNTPROFILEEJB PRIMARY KEY( "USERID" ) )   
	RCDFMT ACCOU00001 ; 
  
  
CREATE OR REPLACE TABLE OCPDT.ACCOUNTEJB ( 
	CREATIONDATE FOR COLUMN CREAT00001 DATE DEFAULT NULL , 
	OPENBALANCE FOR COLUMN OPENB00001 DECIMAL(14, 2) DEFAULT NULL , 
	LOGOUTCOUNT FOR COLUMN LOGOU00001 INTEGER NOT NULL , 
	BALANCE DECIMAL(14, 2) DEFAULT NULL , 
	ACCOUNTID INTEGER NOT NULL , 
	LASTLOGIN DATE DEFAULT NULL , 
	LOGINCOUNT INTEGER NOT NULL , 
	PROFILE_USERID FOR COLUMN PROFI00001 VARCHAR(250) CCSID 37 DEFAULT NULL , 
	CONSTRAINT OCPDT.PK_ACCOUNTEJB PRIMARY KEY( ACCOUNTID ) )   
	  
	RCDFMT ACCOUNTEJB ; 
  
  
CREATE INDEX OCPDT.ACCOUNT_USERID 
	FOR SYSTEM NAME ACCOU00002 ON OCPDT.ACCOUNTEJB ( PROFILE_USERID ASC )   
	; 
  
  
CREATE OR REPLACE TABLE OCPDT.HOLDINGEJB ( 
	PURCHASEPRICE FOR COLUMN PURCH00001 DECIMAL(14, 2) DEFAULT NULL , 
	HOLDINGID INTEGER NOT NULL , 
	QUANTITY DOUBLE PRECISION NOT NULL , 
	PURCHASEDATE FOR COLUMN PURCH00002 DATE DEFAULT NULL , 
	ACCOUNT_ACCOUNTID FOR COLUMN ACCOU00001 INTEGER DEFAULT NULL , 
	QUOTE_SYMBOL FOR COLUMN QUOTE00001 VARCHAR(250) CCSID 37 DEFAULT NULL , 
	CONSTRAINT OCPDT.PK_HOLDINGEJB PRIMARY KEY( HOLDINGID ) )   
	  
	RCDFMT HOLDINGEJB ; 
  
  
CREATE INDEX OCPDT.HOLDING_ACCOUNTID 
	FOR SYSTEM NAME HOLDI00001 ON OCPDT.HOLDINGEJB ( ACCOUNT_ACCOUNTID ASC )   
	; 
  
  
CREATE OR REPLACE TABLE OCPDT.KEYGENEJB ( 
	KEYVAL INTEGER NOT NULL , 
	KEYNAME VARCHAR(250) CCSID 37 NOT NULL , 
	CONSTRAINT OCPDT.PK_KEYGENEJB PRIMARY KEY( KEYNAME ) )   
	  
	RCDFMT KEYGENEJB  ; 
  
  
CREATE OR REPLACE TABLE OCPDT.ORDEREJB ( 
	ORDERFEE DECIMAL(14, 2) DEFAULT NULL , 
	COMPLETIONDATE FOR COLUMN COMPL00001 DATE DEFAULT NULL , 
	ORDERTYPE VARCHAR(250) CCSID 37 DEFAULT NULL , 
	ORDERSTATUS FOR COLUMN ORDER00001 VARCHAR(250) CCSID 37 DEFAULT NULL , 
	PRICE DECIMAL(14, 2) DEFAULT NULL , 
	QUANTITY DOUBLE PRECISION NOT NULL , 
	OPENDATE DATE DEFAULT NULL , 
	ORDERID INTEGER NOT NULL , 
	ACCOUNT_ACCOUNTID FOR COLUMN ACCOU00001 INTEGER DEFAULT NULL , 
	QUOTE_SYMBOL FOR COLUMN QUOTE00001 VARCHAR(250) CCSID 37 DEFAULT NULL , 
	HOLDING_HOLDINGID FOR COLUMN HOLDI00001 INTEGER DEFAULT NULL , 
	CONSTRAINT OCPDT.PK_ORDEREJB PRIMARY KEY( ORDERID ) )   
	  
	RCDFMT ORDEREJB   ; 
  
  
CREATE INDEX OCPDT.CLOSED_ORDERS 
	FOR SYSTEM NAME CLOSE00001 ON OCPDT.ORDEREJB ( ACCOUNT_ACCOUNTID ASC , 	ORDERSTATUS ASC )   
	; 
  
  
CREATE INDEX OCPDT.ORDER_ACCOUNTID 
	FOR SYSTEM NAME ORDER00001 ON OCPDT.ORDEREJB ( ACCOUNT_ACCOUNTID ASC )   
	; 
  
  
CREATE INDEX OCPDT.ORDER_HOLDINGID 
	FOR SYSTEM NAME ORDER00002 ON OCPDT.ORDEREJB ( HOLDING_HOLDINGID ASC )   
	; 
  
  
CREATE OR REPLACE TABLE OCPDT.QUOTEEJB ( 
	LOW DECIMAL(14, 2) DEFAULT NULL , 
	OPEN1 DECIMAL(14, 2) DEFAULT NULL , 
	VOLUME DOUBLE PRECISION NOT NULL , 
	PRICE DECIMAL(14, 2) DEFAULT NULL , 
	HIGH DECIMAL(14, 2) DEFAULT NULL , 
	COMPANYNAME FOR COLUMN COMPA00001 VARCHAR(250) CCSID 37 DEFAULT NULL , 
	SYMBOL VARCHAR(250) CCSID 37 NOT NULL , 
	CHANGE1 DOUBLE PRECISION NOT NULL , 
	CONSTRAINT OCPDT.PK_QUOTEEJB PRIMARY KEY( SYMBOL ) )   
	  
	RCDFMT QUOTEEJB   ; 
INSERT INTO OCPDT.ACCOUNTPROFILEEJB values ( 
	"9328 41st St. SW", 
	"xxx", 
    "uid:0", 
	"uidzero@mealyworm.com", 
	"7736883877370000", 
	"The Master UID 0") ; 